### ISSUE TITLE
Improvements for TypedJSON and Sessions.

### ISSUE THREAD

**Issue by chrhol** [Starcounter/Home#139]
Umbrella for issues aimed to improve the behavior and usage of sessions together with TypedJSON. 

Will be implemented in Starcounter `v2.3.x` (and later)

- [x] Deprecate `json.Session` #133
- [x] Store more than one instance of TypedJSON on session #134
- [x] Deprecate `session.Data` #135
- [x] Auto-create session #136 
- [x] Deprecate `session.PublicViewModel` #137
- [ ] Disallow returning TypedJSON with parent from uri-handler #140
- [x] Flaw in response-handling for TypedJSON and jsonpatch. #171

**Comment by chrhol** [comment]
I said on the last AppArchTF meeting that I was going to do this in one big batch, however I think I'm going to revise that. 

I will do it i three steps, and merge each step to the main branches before continuing on the next. #136 and #137 are the ones that might take some more time to get right so I'll leave them for last.

1. #133, #134, #135
2. #140
3. #136, #137

**Comment by per-samuelsson** [comment]
A question I've been thinking about from time to time: would it be possible to trim the "intellisense-experience" with TypedJson somehow?

I'm sure you guys have discussed this at one point or another, and I think I actually mentioned it to you once @chrhol, but I don't remember the answer 😞 

Basically, I think TypedJson would be more appealing and give better vibes if I did this

**Person.json**
```json
{
  "Name" : "Per Samuelsson"
}
```

and then this

```csharp
var p = new Person();
p.   // Intellisense
```

and all I would see was `.Name` and those things from object.

Today, as we all know, it's all kind of things no one getting introduced to the concept would expect. Mainly because, I think, support for "raw values". Was one idea we had to put those things in a different namespace / partial class, so the would not to be explicitly included, kind of like extension methods of LINQ?

**Comment by chrhol** [comment]
> I'm sure you guys have discussed this at one point or another, and I think I actually mentioned it to you once @chrhol, but I don't remember the answer 😞

I think that's because we never reached a definitive answer, or found a good spot to actually do it (since it will probably break things), and it's always been more prioritized issues to solve. 

> and all I would see was .Name and those things from object.

Maybe only showing properties from JsonByExample and object might be to aim a bit to the extreme side. With that said, most of the things that comes up from intellisense today are things that are rarely (or ever) used in apps, and could be moved out or hidden. 

Let's bring it up in one of the upcoming App architecture meetings and see if we can reach some agreement on the general path to take.

**Comment by per-samuelsson** [comment]
> ...  (since it will probably break things), and it's always been more prioritized issues to solve.

Of course. Totally understand that.

> Maybe only showing properties from JsonByExample and object might be to aim a bit to the extreme side. 

Yep, I actually didn't mean literally. There might of course be functionality from `Json` class that is used frequently, and then of course that stuff should be part of the "simple" API as well.

> Let's bring it up in one of the upcoming App architecture meetings and see if we can reach some agreement on the general path to take.

Sounds like a good idea, if it's a prio. You decide. I just wanted to have my say. I'm fine we push it forward too.

**Comment by chrhol** [comment]
Been quite some time without any updates here. I changed my mind once again and decided to merge everything in one big go, since all issues mentioned here are tied together. Trying to do changes in smaller steps just makes it more difficult. 

Also it was decided last week on the AppArchTF meeting that the issue for allowing root response to be blended should be done before this one, since it's both more important and smaller in scope so I have switched to that one for a short time. 

The plan is to have this issue more or less in place in the end of this week and show it on the next AppArchTF meeting.

**Comment by chrhol** [comment]
This is getting in place. The last task is still to be done. All changes can be found in branch `feature/v2.3/home/139`

I have modified a couple of our apps with the new structure and will show this functionality on the next AappArchTF meeting. 

I will not merge anything to the main branch until we have looked at and discussed the functionality.

**Comment by chrhol** [comment]
There are some things that doesn't work correctly. KitchenSink tests fail in teamcity using a nightly with this feature. I will continue testing, hopefully I will be able to fix this before monday.

**Comment by chrhol** [comment]
Added one more issue that was detected during implementation of one of the other that needs to be solved (#171)

**Comment by chrhol** [comment]
These changes are getting ready to be merged. Still havent done #140 though, and as it looks right now I will not have time to finish that one until my vacation. 

It's still not decided yet, exactly when the merge will be done.

**Comment by chrhol** [comment]
This have been merged and is included from version `2.3.1.6839` and forward. Still some work with documentation so will keep this issue open (but start to close the referenced issues).

**Comment by warpech** [comment]
@chrhol, the changes turned out to be pretty usable. Can you work on the docs for it?

**Comment by chrhol** [comment]
> @chrhol, the changes turned out to be pretty usable. Can you work on the docs for it?

Yeah, will spend some time on this.

**Comment by chrhol** [comment]
Docs have been updated. One issue is still not implemented, but I will close this umbrella issue and keep the separate one open.
